name: app_executa_dbt_datamarts
execution_type: datamarts
owner: Engenharia
start_date: '2026-09-09'
limit_time: '18:03:00'
tabelas_para_checar:
- T_LOJAS
- T_RUN
- T_JUMP
git_repo_schema: TACC.DATAMRS
git_repo_name: TACC.DATAMRS
dbt_project: TACC.DATAMRS
dbt_env: dev
dbt_test_dependency: false
dbt_run_profile: true
git_fetch_dependency: true
check_version_dependency: true
update_version_dependency: true
dbt_run:
- id: datamarts
  cmd: EXECUTE ALL
dbt_profile:
- id: DATAMARTS
  cmd: EXECUTE ALL
outlets_dataset: S3://DATAMRTS
qlik_automation:
  enabled: false
